# ====================================================================================================
#
#     @File:        deployFrontend.yaml
#     @Project:     vehicle-dashboard
#     @Author:      Saif Mahmud
#     @Date:        2025-01-02
#     @Version:     0.1
#     @Contact:     msaifofficial@gmail.com
#
#     @Description: Deploy the frontend of the vehicle-dashboard project to GitHub Pages.
#
# ====================================================================================================

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the vehicle-dashboard repo
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: vmsaif/vehicle-dashboard
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'
      # Step 3: Navigate to the frontend directory and install dependencies
      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      # Step 4: Build the Vite project
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Step 5: Deploy the built files to vehicle-dashboard-static-frontend
      - name: Deploy to GitHub Pages Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: frontend/dist
          external_repository: vmsaif/vehicle-dashboard-static-frontend
          publish_branch: main
          disable_nojekyll: true
          force_orphan: true
